AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket and IAM user to be used with Veeam Capacity Tier. Object Lock is not enabled on the S3 bucket - Immutability Disabled.

Parameters:
  BucketName:
    Description: Bucket name. Bucket names must be globally unique.
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[a-z0-9][a-z0-9\-]*'
    ConstraintDescription: Refer to AWS S3 documentation for name requirements and character limits. https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
  Username:
    Default: veeam-s3-user
    Description: IAM username.
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-]*'
    ConstraintDescription: Refer to AWS IAM documentation for name requirements and character limits. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  IAMUser:
    Type: AWS::IAM::User
    DependsOn:
      - S3Bucket
    Properties:
      Path: /
      UserName: !Ref Username
      Policies:
        - PolicyName: veeam-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetBucketVersioning
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                Resource: "*"

  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn:
      - IAMUser
    Properties:
      UserName: !Ref Username

  # Consider storing the IAM secret key in AWS Secrets Manager for secure storage and access.
  # This option is not enabled by default because secrets stored in AWS Secrets Manager incur a monthly cost. Refer to AWS documentation for details.
  # IAMSecretAccessKey:
  #   Type: AWS::SecretsManager::Secret
  #   UpdateReplacePolicy: Delete
  #   DeletionPolicy: Delete
  #   Properties:
  #     Name: VeeamS3AccessKey
  #     Description: Access key used by Veeam to access S3.
  #     SecretString: !Sub '{"AccessKey":"${IAMAccessKey}","SecretAccessKey":"${IAMAccessKey.SecretAccessKey}"}'

Outputs:
  Region:
    Value: !Ref AWS::Region
    Description: AWS Region

  User:
    Value: !Ref IAMUser
    Description: Veeam S3 IAM user

  AccessKey:
    Value: !Ref IAMAccessKey
    Description: Access key ID of new user

  # Remove the "SecretKey" output if you opt to use AWS Secrets Manager to store the secret key (more secure).
  SecretKey:
    Value: !GetAtt IAMAccessKey.SecretAccessKey
    Description: Secret access key of new user

  S3Bucket:
    Value: !Ref S3Bucket
    Description: Veeam S3 bucket (object lock / immutability is not enabled)
